### ISSUE TITLE
bt asset can get corrupted

### ISSUE THREAD

**Issue by delmarle** [luis-l/BonsaiBehaviourTree#11]
- create a bt asset
- select the asset, open the editor, dont save it
-run the scene and make a gameobject use the bt

the asset in result will be corrupted

**Comment by delmarle** [comment]
Exception thrown while invoking [OnOpenAssetAttribute] method 'Bonsai.Designer.BonsaiWindow:OpenCanvasAsset (int,int)' : NullReferenceException: Object reference not set to an instance of an object
Bonsai.Designer.BonsaiCanvas.CreateNode (Bonsai.Core.BehaviourNode behaviour) (at Assets/BonsaiBehaviourTree-master/Designer/Editor/BonsaiCanvas.cs:49)
Bonsai.Designer.BonsaiCanvas.ReconstructEditorNodes (System.Collections.Generic.IEnumerable`1[T] treeBehaviours) (at Assets/BonsaiBehaviourTree-master/Designer/Editor/BonsaiCanvas.cs:182)
Bonsai.Designer.BonsaiCanvas..ctor (Bonsai.Core.BehaviourTree tree) (at Assets/BonsaiBehaviourTree-master/Designer/Editor/BonsaiCanvas.cs:27)
Bonsai.Designer.BonsaiEditor.SetBehaviourTree (Bonsai.Core.BehaviourTree tree) (at Assets/BonsaiBehaviourTree-master/Designer/Editor/BonsaiEditor.cs:306)
Bonsai.Designer.BonsaiWindow.BuildCanvas () (at Assets/BonsaiBehaviourTree-master/Designer/Editor/BonsaiWindow.cs:196)
Bonsai.Designer.BonsaiWindow.SetTree (Bonsai.Core.BehaviourTree bt, Bonsai.Designer.BonsaiEditor+Mode mode) (at Assets/BonsaiBehaviourTree-master/Designer/Editor/BonsaiWindow.cs:219)
Bonsai.Designer.BonsaiWindow.OpenCanvasAsset (System.Int32 instanceID, System.Int32 line) (at Assets/BonsaiBehaviourTree-master/Designer/Editor/BonsaiWindow.cs:443)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr) (at /Users/builduser/buildslave/unity/build/Modules/IMGUI/GUIUtility.cs:187)

**Comment by luis-l** [comment]
Unable to duplicate.

Following your steps I get a null exception because the blackboard is null. Which is to be expected when creating BehaviourTrees from the CreateAssetMenu. (Blackboard is not set)

At runtime, the assets are not modified. The game objects use a clone of the BT asset, so corruption of the original assets would be unlikely. 

Any BT assets open in an BT Editor window will also be saved before going into Play mode.

Are there other ways you were able to duplicate this issue?

**Comment by luis-l** [comment]
Side note: I pushed a fix so null blackboards are not cloned when a BT Asset is cloned.

**Comment by delmarle** [comment]
i will retry to reproduce today

**Comment by delmarle** [comment]
it is still reproducible:

https://www.youtube.com/watch?v=IBfNhm4JkAg&feature=youtu.be

**Comment by luis-l** [comment]
Pushed a fix.

**Comment by luis-l** [comment]
BT assets are auto saved when the Unity Editor is exiting Edit Mode (before entering play mode) by using EditorApplication.playModeStateChanged

Hopefully this fix makes auto-saving much more stable.

**Comment by delmarle** [comment]
there is an extra bug to fix related to this, 
when entering play mode with unsaved bt not saved and selected:

`NullReferenceException: Object reference not set to an instance of an object
UnityEditor.GameObjectInspector.ClearPreviewCache () (at /Users/builduser/buildslave/unity/build/Editor/Mono/Inspector/GameObjectInspector.cs:210)
UnityEditor.GameObjectInspector.OnDisable () (at /Users/builduser/buildslave/unity/build/Editor/Mono/Inspector/GameObjectInspector.cs:198)
UnityEditor.AssetDatabase:SaveAssets()
Bonsai.Designer.BonsaiSaver:SaveTree(TreeMetaData, BonsaiCanvas) (at Assets/BonsaiBehaviourTree-master/Designer/Editor/BonsaiSaver.cs:192)
Bonsai.Designer.BonsaiSaver:SaveCanvas(BonsaiCanvas, TreeMetaData) (at Assets/BonsaiBehaviourTree-master/Designer/Editor/BonsaiSaver.cs:80)
Bonsai.Designer.BonsaiWindow:QuickSave() (at Assets/BonsaiBehaviourTree-master/Designer/Editor/BonsaiWindow.cs:358)
Bonsai.Designer.BonsaiWindow:OnDisable() (at Assets/BonsaiBehaviourTree-master/Designer/Editor/BonsaiWindow.cs:89)`

in BonsaiSaver line 188 changed the following:

      // Sort the nodes in pre order so it is easier to clone the tree.
      canvas.Tree.SortNodes();

      SaveTreeMetaData(meta, canvas);
      var currentObject = Selection.activeObject;
      Selection.activeObject = null;
      AssetDatabase.SaveAssets();
      Selection.activeObject = currentObject;

**Comment by luis-l** [comment]
Did you reproduce this with the latest changes and with the same steps?

**Comment by delmarle** [comment]
this was reproduced with getting latest
- creating a new bt asset
-open it
-add nodes
-keep it open and assign to component to run it
- play scene

i remember having this issue before also, it is a known unity bug they never fixed
https://forum.unity.com/threads/clearpreviewcache-error.714896/

**Comment by luis-l** [comment]
I unable to replicate on Unity 2019.3.14f1

Ill try to search for alternatives to OnDisable so BT assets can be saved on window close and when a reload occurs.

**Comment by luis-l** [comment]
I pushed a fix in the branch: fix/btsave

This removes saving from OnDisable. 

Saving is done explicitly when the window is destroyed (OnDestroy), before assembly reloads, and before entering play mode.

Could you test the changes in fix/btsave?

**Comment by delmarle** [comment]
i got latest in new project in 2019.3 and i got same error while running a bt & having the window open.
`NullReferenceException: Object reference not set to an instance of an object
UnityEditor.GameObjectInspector.ClearPreviewCache () (at <6f28216fea9f453abf2e05b770ed3ee4>:0)
UnityEditor.GameObjectInspector.OnDisable () (at <6f28216fea9f453abf2e05b770ed3ee4>:0)
UnityEditor.AssetDatabase:SaveAssets()
Bonsai.Designer.BonsaiSaver:SaveTree(TreeMetaData, BonsaiCanvas) (at Assets/BonsaiBehaviourTree-master/Designer/Editor/BonsaiSaver.cs:192)
Bonsai.Designer.BonsaiSaver:SaveCanvas(BonsaiCanvas, TreeMetaData) (at Assets/BonsaiBehaviourTree-master/Designer/Editor/BonsaiSaver.cs:80)
Bonsai.Designer.BonsaiWindow:QuickSave() (at Assets/BonsaiBehaviourTree-master/Designer/Editor/BonsaiWindow.cs:360)
Bonsai.Designer.BonsaiWindow:OnDisable() (at Assets/BonsaiBehaviourTree-master/Designer/Editor/BonsaiWindow.cs:81)
`

**Comment by luis-l** [comment]
> 
> 
> i got latest in new project in 2019.3 and i got same error while running a bt & having the window open.
> `NullReferenceException: Object reference not set to an instance of an object UnityEditor.GameObjectInspector.ClearPreviewCache () (at <6f28216fea9f453abf2e05b770ed3ee4>:0) UnityEditor.GameObjectInspector.OnDisable () (at <6f28216fea9f453abf2e05b770ed3ee4>:0) UnityEditor.AssetDatabase:SaveAssets() Bonsai.Designer.BonsaiSaver:SaveTree(TreeMetaData, BonsaiCanvas) (at Assets/BonsaiBehaviourTree-master/Designer/Editor/BonsaiSaver.cs:192) Bonsai.Designer.BonsaiSaver:SaveCanvas(BonsaiCanvas, TreeMetaData) (at Assets/BonsaiBehaviourTree-master/Designer/Editor/BonsaiSaver.cs:80) Bonsai.Designer.BonsaiWindow:QuickSave() (at Assets/BonsaiBehaviourTree-master/Designer/Editor/BonsaiWindow.cs:360) Bonsai.Designer.BonsaiWindow:OnDisable() (at Assets/BonsaiBehaviourTree-master/Designer/Editor/BonsaiWindow.cs:81) `

This error should be gone in the branch fix/btsave since OnDisable no longer does any saving.

**Comment by delmarle** [comment]
yes it is fixed indeed now, will keep testing more
